# Site settings
gems: [jekyll-paginate]
title: Ship
description: > # this means to ignore newlines until "baseurl:"
  SHIP!

# Build settings
markdown: kramdown

#Collections
collections:
    courses:
        output: true
        permalink: /courses/:categories/:title
    inhouse-trainers:
        output: true
        permalink: /inhouse_trainers/:title